### ISSUE TITLE
Problem when start a process on web page.

### ISSUE THREAD

**Issue by weimeilin79** [eschabell/bpms-fuse-travel-agency-integration-demo#1]
I can't seem to kickstart the process via the web page, get this error when I try to submit the form. 
```
14:50:48,095 INFO  [org.uberfire.backend.server.security.adapter.WebSphereGroupsAdapter] (http-/127.0.0.1:8080-2) Unable to look up UserRegistry in JNDI under key 'UserRegistry', disabling websphere adapter
14:50:48,176 WARN  [org.kie.remote.services.rest.exception.DescriptiveExceptionHandler] (http-/127.0.0.1:8080-2) Exception thrown when processing request [/runtime/org.specialtripsagency:specialtripsagencyproject:2.0.0/process/org.specialtripsagency.specialtripsagencyprocess/start?map_applicantName=Christina+Lin&map_emailAddress=weimeilin%40gmail.com&map_numberOfTravelers=2i&map_preferredDateOfArrival=2015-04-08&map_preferredDateOfDeparture=2015-05-08&map_otherDetails=Nothing&map_fromDestination=London&map_toDestination=Edinburgh]; responding with status 404: org.kie.remote.services.rest.exception.KieRemoteRestOperationException: No deployments available for org.specialtripsagency:specialtripsagencyproject:2.0.0
	at org.kie.remote.services.rest.exception.KieRemoteRestOperationException.notFound(KieRemoteRestOperationException.java:119) [kie-remote-services-6.2.0.Final-redhat-4.jar:6.2.0.Final-redhat-4]
	at org.kie.remote.services.cdi.ProcessRequestBean.doKieSessionOperation(ProcessRequestBean.java:248) [kie-remote-services-6.2.0.Final-redhat-4.jar:6.2.0.Final-redhat-4]
	at org.kie.remote.services.cdi.ProcessRequestBean$Proxy$_$$_WeldClientProxy.doKieSessionOperation(ProcessRequestBean$Proxy$_$$_WeldClientProxy.java) [kie-remote-services-6.2.0.Final-redhat-4.jar:6.2.0.Final-redhat-4]
	at org.kie.remote.services.rest.RuntimeResourceImpl.startProcessInstance(RuntimeResourceImpl.java:351) [kie-remote-services-6.2.0.Final-redhat-4.jar:6.2.0.Final-redhat-4]
	at org.kie.remote.services.rest.RuntimeResourceImpl.startProcessInstance(RuntimeResourceImpl.java:96) [kie-remote-services-6.2.0.Final-redhat-4.jar:6.2.0.Final-redhat-4]
	at org.kie.remote.services.rest.RuntimeResourceImpl$Proxy$_$$_WeldClientProxy.startProcessInstance(RuntimeResourceImpl$Proxy$_$$_WeldClientProxy.java) [kie-remote-services-6.2.0.Final-redhat-4.jar:6.2.0.Final-redhat-4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_60-ea]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_60-ea]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_60-ea]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_60-ea]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:168) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:269) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:227) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:216) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:541) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:523) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:125) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50) [resteasy-jaxrs-2.3.10.Final-redhat-1.jar:]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-2.jar:1.0.2.Final-redhat-2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.kie.remote.services.rest.jaxb.DynamicJaxbContextFilter.doFilter(DynamicJaxbContextFilter.java:48) [kie-remote-services-6.2.0.Final-redhat-4.jar:6.2.0.Final-redhat-4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.uberfire.ext.security.server.BasicAuthSecurityFilter.doFilter(BasicAuthSecurityFilter.java:53) [uberfire-servlet-security-0.5.3.Final-redhat-1.jar:0.5.3.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.uberfire.ext.security.server.SecureHeadersFilter.doFilter(SecureHeadersFilter.java:53) [uberfire-servlet-security-0.5.3.Final-redhat-1.jar:0.5.3.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.uberfire.ext.security.server.SecurityIntegrationFilter.doFilter(SecurityIntegrationFilter.java:64) [uberfire-servlet-security-0.5.3.Final-redhat-1.jar:0.5.3.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:420) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:400) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:854) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_60-ea]

14:50:48,289 ERROR [stderr] (thread-no-98) org.apache.http.HttpException: Failed to POST to rest/runtime/org.specialtripsagency:specialtripsagencyproject:2.0.0/process/org.specialtripsagency.specialtripsagencyprocess/start?map_applicantName=Christina Lin&map_emailAddress=weimeilin@gmail.com&map_numberOfTravelers=2i&map_preferredDateOfArrival=2015-04-08&map_preferredDateOfDeparture=2015-05-08&map_otherDetails=Nothing&map_fromDestination=London&map_toDestination=Edinburgh - http status line = HTTP/1.1 404 Not Found; response content = <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
14:50:48,289 ERROR [stderr] (thread-no-98) <exception>
14:50:48,289 ERROR [stderr] (thread-no-98)     <status>NOT_FOUND</status>
14:50:48,289 ERROR [stderr] (thread-no-98)     <url>http://localhost:8080/business-central/rest/runtime/org.specialtripsagency:specialtripsagencyproject:2.0.0/process/org.specialtripsagency.specialtripsagencyprocess/start?map_applicantName=Christina+Lin&amp;map_emailAddress=weimeilin%40gmail.com&amp;map_numberOfTravelers=2i&amp;map_preferredDateOfArrival=2015-04-08&amp;map_preferredDateOfDeparture=2015-05-08&amp;map_otherDetails=Nothing&amp;map_fromDestination=London&amp;map_toDestination=Edinburgh</url>
14:50:48,290 ERROR [stderr] (thread-no-98) </exception>
14:50:48,290 ERROR [stderr] (thread-no-98) 
14:50:48,290 ERROR [stderr] (thread-no-98) 	at com.externalui.example.client.jbpm.Jbpm6ClientImpl.send(Jbpm6ClientImpl.java:86)
14:50:48,290 ERROR [stderr] (thread-no-98) 	at com.externalui.example.client.jbpm.Jbpm6ClientImpl.startProcessWithMap(Jbpm6ClientImpl.java:49)
14:50:48,291 ERROR [stderr] (thread-no-98) 	at com.externalui.example.client.jbpm.Jbpm6ClientImpl.startProcess(Jbpm6ClientImpl.java:45)
14:50:48,291 ERROR [stderr] (thread-no-98) 	at com.externalui.example.client.jbpm.BpmsClientThread.starBusinessProcess(BpmsClientThread.java:78)
14:50:48,291 ERROR [stderr] (thread-no-98) 	at com.externalui.example.SimpleServlet.doGet(SimpleServlet.java:43)
14:50:48,291 ERROR [stderr] (thread-no-98) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
14:50:48,291 ERROR [stderr] (thread-no-98) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
14:50:48,292 ERROR [stderr] (thread-no-98) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
14:50:48,292 ERROR [stderr] (thread-no-98) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
14:50:48,292 ERROR [stderr] (thread-no-98) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231)
14:50:48,292 ERROR [stderr] (thread-no-98) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
14:50:48,293 ERROR [stderr] (thread-no-98) 	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
14:50:48,293 ERROR [stderr] (thread-no-98) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150)
14:50:48,293 ERROR [stderr] (thread-no-98) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
14:50:48,293 ERROR [stderr] (thread-no-98) 	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:419)
14:50:48,294 ERROR [stderr] (thread-no-98) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
14:50:48,294 ERROR [stderr] (thread-no-98) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
14:50:48,294 ERROR [stderr] (thread-no-98) 	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:854)
14:50:48,294 ERROR [stderr] (thread-no-98) 	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
14:50:48,295 ERROR [stderr] (thread-no-98) 	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926)
14:50:48,295 ERROR [stderr] (thread-no-98) 	at java.lang.Thread.run(Thread.java:744)
```

**Comment by eschabell** [comment]
This was fixed when micro-service processing was completed, services calls needed to be adjusted.
